.TH neostow 1
.SH NAME
.B neostow
\- the declarative GNU stow
.SH SYNOPSIS
.B neostow
.I [OPTION] [ARGUMENT]
.SH DESCRIPTION
neostow is a tool that streamline the process to manage symlinks like GNU stow, but using a configuration file. It allows for more flexible symlink management, enabling the creation of symlinks from anywhere to anywhere on your computer.

This declarative nature allows to easily make reproducible and granular symlinking, unlike GNU Stow. However, this project does not aims to fully replace GNU Stow, but to give a declarative feature missing from it.
.SH OPTIONS
.TP
.B -h, --help
Display the help message and exits.
.TP
.B -d
Remove all existing symlinks from the configuration file.
.TP
.B -p [PARALLEL]

Set how many parallel jobs are used. The default is 20.
.TP
.B -r
Overwrite symlinks, if they already exist.
.TP
.B -c [ABSOLUTE_PATH]

Use different configuration file.
.TP
.B -v
Enable verbose.
.SH FILES

The configuration file is defined as .neostow. By default this file will be looked in the current directory, otherwise explicitly located using the -c option.
.TP
.B Syntax
The syntax consists of a source file/directory and a destination file/directory separated by the equal (=) symbol.
It's allowed to use environment variables in the configuration file.

It's possible to set files and directories, which will be infered by the presence of a backslash.

Next, there is a quick example:

neostow/=$HOME/Download/
.TP
.B Source File
The source file is always defined relatively as the .neostow file. So, if the config file is at the home directory, to specify the Desktop directory, just type it and make sure to add an ending backslash (/).

.TP
.B Destination File
The destination file must be specified as a absolute path, unlike the source file.

.SH BUGS
.TP
.B Shell Injection
By writing a shell command in the configuration file is not adviced, and currently is a major vulnerability.
.SH EXAMPLE

Consider the following example.

.B Configuration Location:
$HOME/dev/neostow

.B Contents:

github/bmark/src/bmark=$HOME/.local/bin/

github/neostow/src/neostow=$HOME/.local/bin/

codeberg/=$HOME/

To properly use this configuration, the -c option is required.

This example will link bmark and neostow files to .local/bin, and the codeberg directory to the home directory.
.SH SEE ALSO
stow(1)
